[colors.primary]
background = "0x000000"
foreground = "0xe6e6e6"

[colors.normal]
black   = "0x0d0d0d"
red     = "0xe55a5a"
green   = "0x5cb370"
yellow  = "0xd4af37"
blue    = "0x42a5c7"
magenta = "0xa85fb5"
cyan    = "0x42b8c7"
white   = "0xe6e6e6"

[colors.bright]
black   = "0x5c6370"
red     = "0xe55a5a"
green   = "0x5cb370"
yellow  = "0xd4af37"
blue    = "0x42a5c7"
magenta = "0xa85fb5"
cyan    = "0x42b8c7"
white   = "0xe6e6e6"


[font]
size = 12

[font.normal]
family = "JetbrainsMonoNL Nerd Font"
style = "Regular"

[font.bold]
family = "JetbrainsMonoNL Nerd Font"
style = "Bold"

[font.italic]
family = "JetbrainsMonoNL Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetbrainsMonoNL Nerd Font"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

[scrolling]
history = 50000

[window]
decorations = "none"
dynamic_padding = false
opacity = 1.00
startup_mode = "Maximized"
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 0
y = 0

[env]
TERM = "xterm-256color"
